trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-pat

parameters:
  - name: service
    displayName: Service Name
    type: string
    default: catalogue

    values:
      - catalogue
      - user
      - cart
      - payment
      - shipping
      - frontend
      - catalogue-schema
      - shipping-schema

stages:

  - stage: BuildAndPush
    displayName: Build And Push

    jobs:

      - job: Build

        steps:

          - checkout: self

          - task: Docker@2
            displayName: Build And Push Image

            inputs:
              containerRegistry: sameerroboshopacr
              repository: ${{ parameters.service }}
              command: buildAndPush
              Dockerfile: '${{ parameters.service }}/Dockerfile'

              tags: |
                $(Build.BuildId)

  - stage: Approval
    displayName: Manual Approval

    dependsOn: BuildAndPush

    jobs:

      - deployment: WaitForApproval

        environment: production

        strategy:

          runOnce:

            deploy:

              steps:

                - script: echo "Approved"

  - stage: UpdateGitOps

    dependsOn: Approval

    jobs:

      - job: UpdateManifest

        steps:

          - checkout: none

          - script: |

              git clone https://$(GITHUB_TOKEN)@github.com/Sameer-Sarrainodu/ecommerce-gitops.git

              cd ecommerce-gitops

              sed -i "s/tag:.*/tag: $(Build.BuildId)/" helm/${{ parameters.service }}/values.yaml

              git config user.email "azuredevops@local"
              git config user.name "azure-pipeline"

              git add helm/${{ parameters.service }}/values.yaml

              git commit -m "${{ parameters.service }} image $(Build.BuildId)"

              git push

            env:
              GITHUB_TOKEN: $(GITHUB_TOKEN)